# Generated by Django 3.0.3 on 2020-05-15 07:38

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=music.models.artist_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('song_file', models.FileField(null=True, upload_to=music.models.song_directory_path)),
                ('artists', models.ManyToManyField(related_name='songs', to='music.Artist')),
            ],
        ),
    ]
