# Generated by Django 3.0.3 on 2020-06-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20200613_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
