# Generated by Django 3.0.3 on 2020-04-30 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_categoria', '0001_initial'),
        ('admin_alimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_categoria.Categoria'),
        ),
    ]
