# Generated by Django 3.0.3 on 2020-06-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_alimentos', '0002_auto_20200430_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='foto',
            field=models.ImageField(blank=True, upload_to='static/img'),
        ),
    ]
